--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/superbobby2000/VanishV2
branches:
- master
- "4.0"
projects:
  VanishV2:
    path: ""
    icon: icon.png
    libs:
      - src: muqsit/InvMenu/InvMenu
        version: ^4.4.1
        branch: "4.0"
...
